### ISSUE TITLE
"The method eth_sendTransaction does not exist/ is not available"

### ISSUE THREAD

**Issue by victorylau** [Boilertalk/Web3.swift#126]

**Comment by koraykoska** [comment]
@victorylau We do not officially support methods that encourage behaviour that is deprecated due to obvious security concerns. You can add any methods using `extension` functions. Simply look at the `Web3` class and copy the `eth.sendRawTransaction`, modify it to match whatever request you want to support and rename it. That way you can support any method you want with a few lines of code.

A good read about

**Comment by koraykoska** [comment]
See #116

**Comment by victorylau** [comment]
> @victorylau We do not officially support methods that encourage behaviour that is deprecated due to obvious security concerns. You can add any methods using `extension` functions. Simply look at the `Web3` class and copy the `eth.sendRawTransaction`, modify it to match whatever request you want to support and rename it. That way you can support any method you want with a few lines of code.
> 
> A good read about

Thanks a lot. I resolve my problem.
