### ISSUE TITLE
ABIDecoder crashes on some wrong outputs

### ISSUE THREAD

**Issue by Ybrin** [Boilertalk/Web3.swift#44]
I tried getting the symbol of an erc20 token (https://etherscan.io/address/0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0) and the decoder crashed.        
[This line](https://github.com/Boilertalk/Web3.swift/blob/master/Web3/Classes/ContractABI/ABI/ABIDecoder.swift#L44) fails and the error is "Can't remove first element from an empty collection".

I don't know the exact reason. Maybe this ERC20 token is broken. The symbol type is bytes32 and not string if we can believe etherscan. But whatever it is, the decoder shouldn't crash.

**Comment by Ybrin** [comment]
@pixelmatrix Please have a look

**Comment by pixelmatrix** [comment]
Will do! Thanks for flagging

**Comment by pixelmatrix** [comment]
Hm, yeah so it looks like the reason this is crashing is that it isn't checking to make sure the range exists before trying to remove the first element. We should absolutely fix this, but I think you ultimately wouldn't get the value you're looking for without the crash. Bytes32 would be non-dynamic so the value would be in the head, while the String type would expect value in the tail.

Are you using the `GenericERC20Contract` from this library, or a custom class / the ABI from etherscan? This particular contract may not be compatible with `AnnotatedERC20` since that is an optional sub-protocol.

**Comment by Ybrin** [comment]
I'm using `GenericERC20Contract ` and the contract is definitely not compatible. But the crash shouldn't happen nevertheless. The response will be nonsense though...
