### ISSUE TITLE
Contract ABI fallback functions

### ISSUE THREAD

**Issue by Nixsm** [Boilertalk/Web3.swift#48]
The `ABIObject` always expect inputs, which is not correct if the contract contains a fallback function, a possible fix would be changing the `parameters` to be optional

**Comment by Ybrin** [comment]
I think the fallback function is not a real function. It is actually only called if you don't provide any extra data which essentially means you just send a normal transaction.    
So I think instead of having the fallback function in your contract definition you should just create a normal transaction to the contract account and don't provide extra data. You could also add a convenient function to the contract definition which does exactly this.

@pixelmatrix Could you clarify this if I am missing something?

**Comment by pixelmatrix** [comment]
Yes, as far as I understand, the fallback function is executed when you send ETH to a contract without any instructions. According to the spec, there are no inputs or outputs allowed:
http://solidity.readthedocs.io/en/v0.4.24/abi-spec.html#json

@Nixsm are you saying you want to use the fallback function somehow, or that you're having trouble decoding a contract that has a fallback function?

**Comment by Nixsm** [comment]
@pixelmatrix I'm having trouble parsing a contract that has a callback function, I get an error saying that the `inputs` field is required

**Comment by Nixsm** [comment]
This JSON is invalid for the `ABIObject`:
```
{
    "payable": true,
    "stateMutability": "payable",
    "type": "fallback"
}
```
But it's a valid Solidity function
